on:
  push:
    branches:
      - ja

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: generate-markdown
        run: |
          cat i18n/ja_JP/LC_MESSAGES/gamedata.po i18n/ja_JP/LC_MESSAGES/messages.po \
            | ./utils/translationprogress \
            | perl -anal -e 'BEGIN { print qq(| File | Progress | % |\n| -- | -- | -- |) } printf qq(| [$F[0]](../blob/HEAD/$F[0]) | $F[1]/$F[2] | ![%.1f%%](https://progress-bar.dev/%d/) |\n), $F[1]/$F[2]*100, $F[1]/$F[2]*100' \
            | sed -z 's/\n/\\n/g' \
            | sed 's/^/body=/' \
            >> $GITHUB_OUTPUT

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: 3,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{steps.generate-markdown.outputs.body}}'.replace(/\\n/g, '\n')
            })
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          curl -LO https://github.com/motemen/clang-tidy-check-extra-i18n-string/releases/download/v0.4.0/libExtraI18nStringCheck_14.so

      - id: generate-markdown
        run: |
          echo '| File | Progress | % |' >> "$GITHUB_OUTPUT"
          echo '| -- | -- | -- |' >> "$GITHUB_OUTPUT"
          for file in src/*.c; do
            clang-tidy \
              -load=./libExtraI18nStringCheck_14.so \
              -config-file=.github/workflows/clang-tidy \
              "$file" \
              -- -DUSE_LOCALE -DUSE_DOUBLEWIDTH -DLOCALE_NO_WORD_DIVIDER \
            | perl -nle '
              BEGIN { $file = shift }
              /\bwarning:/ and $bad++;
              /\bremark:/ and $good++;
              END {
                $good ||= 0;
                $total = $good + $bad;
                printf qq(| [$file](../blob/HEAD/$file) | $good/$total | ![%.1f%%](https://progress-bar.dev/%d/)\n),
                  ($total ? $good/$total*100 : 100) x 2
              }' "$file"
          done >> "$GITHUB_OUTPUT"
          sed -i -z 's/\n/\\n/g;s/^/body=/' "$GITHUB_OUTPUT"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: 4,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{steps.generate-markdown.outputs.body}}'.replace(/\\n/g, '\n')
            })
