on:
  push:
    branches:
      - test-i18n-progress

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          curl -LO https://github.com/motemen/clang-tidy-check-extra-i18n-string/releases/download/v0.3.0/libExtraI18nStringCheck_14.so

      - id: generate-markdown
        run: |
          echo '| File | Progress | % |' >> "$GITHUB_OUTPUT"
          echo '| -- | -- | -- |' >> "$GITHUB_OUTPUT"
          for file in src/*.c; do
            clang-tidy \
              -load=./libExtraI18nStringCheck_14.so \
              -config-file=.github/workflows/clang-tidy \
              "$file" \
              -- -DUSE_LOCALE -DUSE_DOUBLEWIDTH -DLOCALE_NO_WORD_DIVIDER \
            | perl -nle '
              BEGIN { $file = shift }
              /\bwarning:/ and $bad++;
              /\bremark:/ and $good++;
              END {
                $good ||= 0;
                $total = $good + $bad;
                printf qq(| [$file](../blob/HEAD/$file) | $good/$total | ![%.1f%%](https://progress-bar.dev/%d/)\n),
                  ($total ? $good/$total*100 : 100) x 2
              }' "$file"
          done >> "$GITHUB_OUTPUT"
          sed -i -z 's/\n/\\n/g;s/^/body=/' "$GITHUB_OUTPUT"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: 4,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{steps.generate-markdown.outputs.body}}'.replace(/\\n/g, '\n')
            })
