on:
  push:
    branches:
      - test-i18n-progress

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          env
          sudo apt-get update
          sudo apt-get install -y "libclang-14-dev"

      - run: |
          export CC=clang-14 CXX=clang++-14
          cmake -S utils/i18nhound -B utils/i18nhound/build -DLLVM_DIR=/usr/lib/llvm-14/lib/cmake/llvm -DCLANG_DIR=/usr/lib/llvm-14/lib/cmake/clang
          cmake --build utils/i18nhound/build
