on:
  push:
    branches:
      - test-i18n-progress

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          env
          apt-get update
          apt-get install -y "libclang-14-dev"

      - run: |
          cmake -S utils/i18nhound -B utils/i18nhound/build
          cmake --build utils/i18nhound/build
